version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

pre_build:
  commands:
    - chmod +x build_docker_image.sh push_image.sh
    - ./build_docker_image.sh 

build:
  commands:
    - ./push_image.sh